# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 19:15
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profiles_for_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
