# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_linkedin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='year_of_birth',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='filled_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_language',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
