# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_rename_edx_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
