# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_profile_verified_micromaster_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_url_full',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_url_large',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_url_medium',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_url_small',
        ),
    ]
