# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-31 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_change_default_of_account_privacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_state_or_territory',
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.TextField(blank=True, null=True),
        ),
    ]
