# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-26 17:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='edx_language_proficiencies',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
