# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import profiles.util


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_add_address_and_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to=profiles.util.profile_image_upload_uri),
        ),
    ]
