# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_truncate_profile_image_uri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='has_profile_image',
        ),
    ]
