# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_remove_profile_linkedin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_country_code',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
