# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 20:14
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_merge_address_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mail_id',
            field=models.UUIDField(default=uuid.uuid4, unique=False),
        ),
    ]
