# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 20:14
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    """Generate unique UUID values"""
    Profile = apps.get_model('profiles', 'Profile')
    for profile in Profile.objects.all():
        profile.mail_id = uuid.uuid4()
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_create_mail_id'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
