# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_data_migration_for_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fake_user',
            field=models.BooleanField(default=False),
        ),
    ]
