# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 15:59
from __future__ import unicode_literals

from django.db import migrations


def mark_all_fake_profiles(apps, schema_editor):
    Profile = apps.get_model("profiles", "Profile")
    Profile.objects.filter(user__username__startswith='fake.').update(fake_user=True)


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_profile_fake_user'),
    ]

    operations = [
        migrations.RunPython(mark_all_fake_profiles, migrations.RunPython.noop)
    ]
