# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


homepage_props = dict(
    slug='home',
    path='00010001'
)


def create_homepage(apps, schema_editor):
    # Get models
    ContentType = apps.get_model('contenttypes.ContentType')
    Page = apps.get_model('wagtailcore.Page')
    HomePage = apps.get_model('cms.HomePage')
    Site = apps.get_model('wagtailcore.Site')

    # Delete the default homepage
    Page.objects.filter(id=2).delete()

    # Create content type for homepage model
    homepage_content_type, created = ContentType.objects.get_or_create(
        model='homepage', app_label='cms')

    # Create a new homepage
    homepage_defaults = dict(
        title="Homepage",
        content_type=homepage_content_type,
        depth=2,
        numchild=0,
        url_path='/home/',
    )
    homepage, _ = HomePage.objects.get_or_create(
        **homepage_props,
        defaults=homepage_defaults
    )

    # Create a site with the new homepage set as the root
    Site.objects.get_or_create(
        hostname='localhost', root_page=homepage, is_default_site=True)


def remove_homepage(apps, schema_editor):
    Page = apps.get_model('wagtailcore.Page')
    HomePage = apps.get_model('cms.HomePage')
    HomePage.objects.filter(**homepage_props).delete()
    # Just in case the above deletion didn't get rid of the Page record...
    Page.objects.filter(**homepage_props).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_programpage_program'),
    ]

    operations = [
        migrations.RunPython(create_homepage, reverse_code=remove_homepage),
    ]
