# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0012_copy_image_permissions_to_collections'),
        ('cms', '0004_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='title_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
    ]
