# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 17:12
from __future__ import unicode_literals

from django.db import migrations

def set_default_homepage_text(apps, schema_editor):
    HomePage = apps.get_model("cms", "HomePage")
    homepage = HomePage.objects.first()
    homepage.title = ("MIT credentials are now attainable by "
        "anyone in the world with the discipline, dedication, and "
        "intelligence to master course material.")
    homepage.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_add_homepage_image'),
    ]

    operations = [
        migrations.RunPython(set_default_homepage_text, reverse_code=migrations.RunPython.noop),
    ]
