# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 16:26
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_programpage_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpage',
            name='contact_us',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
