# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 16:28
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_programpage_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpage',
            name='title_over_image',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
