# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_programpage_title_over_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpage',
            name='external_program_page_url',
            field=models.URLField(blank=True, help_text='Use this field to directly link an external web page for this program.', null=True),
        ),
    ]
