# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-15 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_add_home_page_and_email_to_program_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programpage',
            name='contact_us',
        ),
    ]
