# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-29 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_update_programfaculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='title_background',
        ),
    ]
