# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-07 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('cms', '0019_removed_fields_cms_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='frequentlyaskedquestion',
            name='program_page',
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='faqs_page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='cms.FaqsPage'),
        ),
    ]
