# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-11 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('cms', '0021_remove_frequentlyaskedquestion_faqs_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorizedFaqsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='faqs_page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='cms.CategorizedFaqsPage'),
        ),
    ]
