# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-25 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_add_categorized_faqs_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpage',
            name='title_program_home_page_url',
            field=models.TextField(blank=True, help_text='The text for the link to an external homepage.'),
        ),
    ]
