# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-20 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('cms', '0022_add_categorized_faqs_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqspage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='FaqsPage',
        ),
    ]
