# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_frequentlyaskedquestion_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('semester_name', models.CharField(help_text='Name for the semester. For example: "Fall" or "Fall 2018"', max_length=50)),
                ('start_date', models.DateField()),
                ('program_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_dates', to='cms.ProgramPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
