# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_remove_unused_fields'),
        ('cms', '0027_semesterdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='programcourse',
            name='course',
            field=models.OneToOneField(help_text='The course for this ProgramCourse', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Course'),
        ),
    ]
