# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 20:37
from __future__ import unicode_literals

from django.db import migrations


def populate_program_courses(apps, schema_editor):
    ProgramCourse = apps.get_model('cms', 'ProgramCourse')
    ProgramPage = apps.get_model('cms', 'ProgramPage')

    ProgramCourse.objects.all().delete()
    program_pages = ProgramPage.objects.all()

    for program_page in program_pages:
        courses = program_page.program.course_set.all()
        for course in courses:
            ProgramCourse.objects.create(
                course=course,
                title=course.title,
                description=course.description,
                program_page=program_page
            )


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_programcourse_course'),
        ('courses', '0025_remove_unused_fields')
    ]

    operations = [
        migrations.RunPython(populate_program_courses, reverse_code=migrations.RunPython.noop),
    ]
