# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-27 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0032_signatories_related_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programpage',
            name='external_program_page_url',
        ),
    ]
