# Generated by Django 2.1.2 on 2019-01-15 12:04

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0033_remove_programpage_external_program_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programtabpage',
            name='content',
            field=wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock()), ('course_table', wagtail.contrib.table_block.blocks.TableBlock(table_options={'startCols': 2, 'startRows': 3}))], blank=True, help_text='The content of this tab on the program page'),
        ),
    ]
