# Generated by Django 2.1.2 on 2019-01-22 09:46

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_data_migration_for_content_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programtabpage',
            name='content',
            field=wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock()), ('course_table', wagtail.contrib.table_block.blocks.TableBlock(table_options={'renderer': 'html', 'startCols': 2, 'startRows': 3}))], blank=True, help_text='The content of this tab on the program page'),
        ),
    ]
