# Generated by Django 2.1.11 on 2019-12-12 19:27

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0043_programpage_program_letter_footer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpage',
            name='program_letter_header_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Header text that will appear next to the logo.', null=True),
        ),
    ]
