# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-26 17:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_create_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
