# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-29 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_switch_jsonfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='course_key',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('fulfilled', 'fulfilled'), ('failed', 'failed')], db_index=True, default='created', max_length=30),
        ),
    ]
