# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-19 21:45
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0006_new_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('data_before', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('data_after', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('acting_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
