# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_coupon_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.TextField(blank=True, help_text='The coupon code used for redemption by the purchaser in the user interface.\n    If blank, the purchaser may not redeem this coupon through the user interface,\n    though it may be redeemed in their name by an administrator.', null=True, unique=True),
        ),
    ]
