# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_unique_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount_type',
            field=models.CharField(choices=[('percent-discount', 'percent-discount'), ('fixed-discount', 'fixed-discount'), ('fixed-price', 'fixed-price')], help_text='Whether amount is a percent or fixed discount', max_length=30),
        ),
    ]
