# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_invoice'),
        ('courses', '0023_add_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprice',
            name='course_run',
        ),
        migrations.DeleteModel(
            name='CoursePrice',
        ),
    ]
