# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-22 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_courserungradingstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalgrade',
            name='course_run_paid_on_edx',
            field=models.BooleanField(default=False),
        ),
    ]
