# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_proctoredexamgrade_proctoredexamgradeaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoredexamgrade',
            name='exam_date',
            field=models.DateTimeField(default=django.utils.timezone.now),  # this works only because we have no data in the DB right now
            preserve_default=False,
        ),
    ]
