# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 20:34
from __future__ import unicode_literals

from django.db import migrations

PILOT_SERIES_CODE = 'PILOT'


def populate_exam_run_fk(apps, schema_editor):
    ExamRun = apps.get_model('exams', 'ExamRun')
    ProctoredExamGrade = apps.get_model('grades', 'ProctoredExamGrade')

    pilot_runs = ExamRun.objects.filter(exam_series_code=PILOT_SERIES_CODE)

    for pilot_run in pilot_runs:
        for grade in ProctoredExamGrade.objects.filter(course=pilot_run.course):
            grade.exam_run = pilot_run
            grade.save()


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0006_add_exam_run_fk'),
    ]

    operations = [
        migrations.RunPython(populate_exam_run_fk, migrations.RunPython.noop)
    ]
