# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-23 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0009_micromasterscoursecertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micromasterscoursecertificate',
            name='final_grade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='grades.FinalGrade'),
        ),
    ]
