# Generated by Django 2.0.2 on 2018-07-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0015_remove_final_grade_field'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE RULE delete_protect AS ON DELETE TO grades_finalgradeaudit DO INSTEAD NOTHING",
            reverse_sql="DROP RULE delete_protect ON grades_finalgradeaudit",
        ),
        migrations.RunSQL(
            sql="CREATE RULE update_protect AS ON UPDATE TO grades_finalgradeaudit DO INSTEAD NOTHING",
            reverse_sql="DROP RULE update_protect ON grades_finalgradeaudit",
        ),
    ]
