# Generated by Django 2.1.5 on 2019-02-27 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_added_course_number_to_course_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grades', '0016_protect_final_grade_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicromastersProgramCommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='micromastersprogramcommendation',
            unique_together={('user', 'program')},
        ),
    ]
