# Generated by Django 2.1.5 on 2019-03-07 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0017_micromastersprogramcommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalgrade',
            name='grade',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
