# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-22 16:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_program_financial_aid_availability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_programenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedCurrentGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField(null=True)),
                ('last_request', models.DateTimeField()),
                ('course_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseRun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='cachedcurrentgrade',
            unique_together=set([('user', 'course_run')]),
        ),
    ]
