# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 21:31
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_all_cache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cachedcertificate',
            name='last_request',
        ),
        migrations.RemoveField(
            model_name='cachedcurrentgrade',
            name='last_request',
        ),
        migrations.RemoveField(
            model_name='cachedenrollment',
            name='last_request',
        ),
        migrations.AlterField(
            model_name='cachedcertificate',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='cachedcurrentgrade',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='cachedenrollment',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='usercacherefreshtime',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
