# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 13:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0012_program_financial_aid_availability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('url', models.TextField()),
                ('sku', models.CharField(max_length=50)),
                ('course_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseRun')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'created'), ('approved', 'approved'), ('auto-approved', 'auto-approved'), ('rejected', 'rejected'), ('pending_docs', 'pending_docs'), ('pending_manual_approval', 'pending_manual_approval')], default='created', max_length=30)),
                ('income_usd', models.FloatField(null=True)),
                ('original_income', models.FloatField(null=True)),
                ('original_currency', models.CharField(max_length=10, null=True)),
                ('country_of_income', models.CharField(max_length=100, null=True)),
                ('exchange_rate', models.FloatField(null=True)),
                ('date_exchange_rate', models.DateTimeField(null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Program')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialAidAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_changed', models.CharField(max_length=50)),
                ('data_before', jsonfield.fields.JSONField(blank=True)),
                ('data_after', jsonfield.fields.JSONField(blank=True)),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TierProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('current', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Program')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financialaid.Tier')),
            ],
        ),
        migrations.AddField(
            model_name='financialaid',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financialaid.TierProgram'),
        ),
        migrations.AddField(
            model_name='financialaid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='financial_aid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financialaid.FinancialAid'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='financial_aid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financialaid.FinancialAid'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tierprogram',
            unique_together=set([('program', 'tier')]),
        ),
    ]
