# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-19 20:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import pytz

class Migration(migrations.Migration):

    dependencies = [
        ('financialaid', '0002_altered_financialaid_and_tierprogram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='course_run',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='financial_aid',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
        migrations.RemoveField(
            model_name='document',
            name='financial_aid',
        ),
        migrations.AddField(
            model_name='financialaid',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 19, 20, 49, 9, 163340, tzinfo=pytz.UTC)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialaid',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 19, 20, 49, 15, 251688, tzinfo=pytz.UTC)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialaidaudit',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 19, 20, 49, 28, 458443, tzinfo=pytz.UTC)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialaidaudit',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 19, 20, 49, 33, 212715, tzinfo=pytz.UTC)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tier',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 19, 20, 49, 36, 384897, tzinfo=pytz.UTC)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tier',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 19, 20, 49, 39, 48049, tzinfo=pytz.UTC)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tierprogram',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 19, 20, 49, 42, 224231, tzinfo=pytz.UTC)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tierprogram',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 19, 20, 49, 44, 842380, tzinfo=pytz.UTC)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financialaid',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('approved', 'approved'), ('auto-approved', 'auto-approved'), ('rejected', 'rejected'), ('pending-docs', 'pending-docs'), ('pending-manual-approval', 'pending-manual-approval')], default='created', max_length=30),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
