# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-04 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialaid', '0009_added_choice_to_financialaid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaid',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('approved', 'approved'), ('auto-approved', 'auto-approved'), ('rejected', 'rejected'), ('pending-docs', 'pending-docs'), ('docs-sent', 'docs-sent'), ('pending-manual-approval', 'pending-manual-approval'), ('skipped', 'skipped')], default='created', max_length=30),
        ),
    ]
