# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-06 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialaid', '0011_remove_rejected_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaid',
            name='date_documents_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
