# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-07 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialaid', '0014_financial_aid_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryIncomeThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('country_code', models.CharField(max_length=2)),
                ('income_threshold', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
