# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-13 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialaid', '0016_load_country_income_thresholds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryincomethreshold',
            name='country_code',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
