# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialaid', '0020_financialaid_country_of_residence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaid',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('auto-approved', 'auto-approved'), ('created', 'created'), ('docs-sent', 'docs-sent'), ('pending-docs', 'pending-docs'), ('pending-manual-approval', 'pending-manual-approval'), ('skipped', 'skipped'), ('reset', 'reset')], default='created', max_length=30),
        ),
    ]
