# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_add_exam_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='examauthorization',
            name='exam_taken',
            field=models.BooleanField(default=False),
        ),
    ]
