# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examauthorization_exam_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='examprofile',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='examprofile',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
