# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_populate_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examprofile',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='examprofile',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
