# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_populate_exam_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examauthorization',
            name='exam_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_authorizations', to='exams.ExamRun'),
        ),
    ]
