# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_remove_unused_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='examauthorization',
            name='exam_no_show',
            field=models.BooleanField(default=False),
        ),
    ]
