# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_remove_unused_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='examrun',
            name='date_grades_available',
            field=models.DateTimeField(null=True),
        ),
    ]
