# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_populate_date_grades_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examrun',
            name='date_grades_available',
            field=models.DateTimeField(),
        ),
    ]
