# Generated by Django 2.2.13 on 2020-09-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_added_description_and_course_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='examauthorization',
            name='exam_coupon_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
