# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


# NOTE: this is altered from the 0001-0004 migrations that are squashed to fix a Django 1.11 upgrade issue. In particular
# Course was created and then renamed to CourseRun, where here it is created as it should be without the rename.

class Migration(migrations.Migration):

    replaces = [('courses', '0001_initial'), ('courses', '0002_rename_course_to_courserun'), ('courses', '0003_course'), ('courses', '0004_courserun_course')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('edx_course_key', models.CharField(blank=True, max_length=255, null=True)),
                ('enrollment_start', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('enrollment_url', models.URLField(blank=True, null=True)),
                ('prerequisites', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('live', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='courserun',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Program'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('prerequisites', models.TextField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Program')),
            ],
        ),
        migrations.AddField(
            model_name='courserun',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
