# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
