# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 15:18
# pylint: disable=unused-argument
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    CourseRun = apps.get_model('courses', 'CourseRun')

    for run in CourseRun.objects.filter(course__isnull=True):
        course, _ = Course.objects.get_or_create(
            title=run.title, program=run.program)
        if run.prerequisites:
            course.prerequisites = run.prerequisites
            course.save()
        run.course = course
        run.save()

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courserun_course'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=lambda apps, schema_editor: None),
    ]
