# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_data_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserun',
            name='program',
        ),
        migrations.AddField(
            model_name='courserun',
            name='fuzzy_start_date',
            field=models.CharField(blank=True, help_text="If you don't know when your course will run exactly, put something here like 'Fall 2019'.", max_length=255, null=True),
        ),
    ]
