# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_position_in_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courserun',
            name='enrollment_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
