# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_courserun_fuzzy_enrollment_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
