# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-13 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_courserun_upgrade_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='financial_aid_availability',
            field=models.BooleanField(default=False),
        ),
    ]
