# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-29 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_program_financial_aid_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserun',
            name='edx_course_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
