# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-12 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_new_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='ga_tracking_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
