# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-19 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_position_in_program_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserun',
            name='edx_course_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
