# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_courserun_freeze_grade_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exam_module',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='exam_series_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
