# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_add_exam_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
