# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_add_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
