# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_add_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='exam_module',
        ),
        migrations.RemoveField(
            model_name='program',
            name='exam_series_code',
        ),
    ]
