# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-19 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_course_should_display_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
