# Generated by Django 2.1.10 on 2019-07-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_course_electives'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='electivecourse',
            unique_together={('course', 'electives_set')},
        ),
    ]
