# Generated by Django 2.1.11 on 2019-10-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_blank_edx_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='topics', to='courses.Topic'),
        ),
    ]
