FROM mitodl/mm_watch_travis

WORKDIR /src

COPY package.json /src

COPY npm-shrinkwrap.json /src

ADD ./webpack_if_prod.sh /src

USER mitodl

RUN mv ./node_modules ./node_modules.tmp && mv ./node_modules.tmp ./node_modules && npm install

COPY . /src

USER root

RUN chown -R mitodl:mitodl /src

USER mitodl
