FROM mitodl/mm_web_travis

WORKDIR /tmp

USER root

COPY requirements.txt /tmp/requirements.txt
COPY test_requirements.txt /tmp/test_requirements.txt
RUN pip install -r requirements.txt && pip install -r test_requirements.txt

WORKDIR /src

COPY . /src

RUN chown -R mitodl:mitodl /src

USER mitodl
