FROM mitodl/mm_watch_travis_next_0919

WORKDIR /src

COPY package.json /src

COPY yarn.lock /src

ADD ./webpack_if_prod.sh /src

USER node

RUN yarn install --pure-lockfile

COPY . /src

USER root

RUN chown -R node:node /src

USER node
