FROM mitodl/micromasters_web_travis_8d7ffc

WORKDIR /tmp

USER root

COPY requirements.txt /tmp/requirements.txt
COPY test_requirements.txt /tmp/test_requirements.txt
RUN pip install -r requirements.txt && pip install -r test_requirements.txt

# mm_web_travis comes with a copy of the source which may not match the current copy, so we need to copy it again
RUN rm -rf /src
RUN mkdir /src

WORKDIR /src

COPY . /src

RUN chown -R mitodl:mitodl /src

# Set pip cache folder, as it is breaking pip when it is on a shared volume
ENV XDG_CACHE_HOME /tmp/.cache

USER mitodl
