FROM mitodl/micromasters_web_travis_8d7ffc

WORKDIR /tmp

USER root

# mm_web_travis comes with a copy of the source which may not match the current copy, so we need to copy it again
RUN rm -rf /src
RUN mkdir /src

WORKDIR /src

COPY . /src

RUN chown -R mitodl:mitodl /src

USER mitodl
