# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-24 13:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0003_percolatequery_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercolateQueryMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_member', models.BooleanField(default=False)),
                ('needs_update', models.BooleanField(default=False)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percolate_memberships', to='search.PercolateQuery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percolate_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='percolatequerymembership',
            unique_together=set([('user', 'query')]),
        ),
    ]
