# Generated by Django 2.1.5 on 2019-03-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_add_percolate_query_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='percolatequery',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
