# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaidemailaudit',
            name='email_body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='financialaidemailaudit',
            name='email_subject',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='financialaidemailaudit',
            name='from_email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='financialaidemailaudit',
            name='to_email',
            field=models.TextField(),
        ),
    ]
