# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
        ('mail', '0003_protect_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomaticEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('email_subject', models.TextField(blank=True)),
                ('email_body', models.TextField(blank=True)),
                ('sender_name', models.TextField(blank=True)),
                ('query', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.PercolateQuery')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
