# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 15:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0005_sentautomaticemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='automaticemail',
            name='staff_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
