# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_automaticemail_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentautomaticemail',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('sent', 'sent')], default='pending', max_length=30),
        ),
    ]
