# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-08 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_percolatequery_source_type'),
        ('discussions', '0001_add_discussion_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('query', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.PercolateQuery')),
            ],
        ),
    ]
