# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-29 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_remove_unused_fields'),
        ('discussions', '0002_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussions.Channel')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Program')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='channelprogram',
            unique_together=set([('channel', 'program')]),
        ),
    ]
