# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-19 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0004_channel_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='discussionuser',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discussionuser',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
