# Generated by Django 2.1.5 on 2019-03-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0005_timestamped_discussions_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
